name: EpiActions

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  EXECUTABLES: "exec"

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
        - name: check_out_repo_code
          uses: actions/checkout@v4
        - name: Make compilation
          run: make
          timeout-minutes: 2
        - name: Make clean compilation
          run: make clean
  
  run_tests:
    runs-on: ubuntu-latest
    needs: [check_program_compilation]
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: check_out_repo_codee
        uses: actions/checkout@v4
      - name: MakeTest compilation
        run: make tests_run
        timeout-minutes: 2
