name: EpiActions

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  EXECUTABLES: "exec"

jobs:
  check_coding_style:
    name: check_coding_style
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
        - name: check_coding_style
          uses: actions/checkout@v4

        - name: "coding style error"
          id: check_coding_style
          run: |
              check.sh "$(pwd)" "$(pwd)"
              if [ -s "$(pwd)/coding-style-reports.log" ]; then
                awk -F ":" '{
                  print "::error title="$3" coding style error,file="$1",line="$2"::" $4
                }' coding-style-reports.log
                exit 1
              fi
                exit 0

  check_program_compilation:
    runs-on: ubuntu-latest
    needs: [check_coding_style]
    container:
      image: epitechcontent/epitest-docker
    steps:
        - name: check_out_repo_code
          uses: actions/checkout@v4
        - name: Make compilation
          run: make
          timeout-minutes: 2
        - name: Make clean compilation
          run: make clean
  
  run_tests:
    runs-on: ubuntu-latest
    needs: [check_program_compilation]
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: check_out_repo_codee
        uses: actions/checkout@v4
      - name: MakeTest compilation
        run: make tests_run
        timeout-minutes: 2
